"""Configuracion inicial e inyeccion de precios

Revision ID: 7fddb8d73cfa
Revises: 
Create Date: 2026-07-17 02:04:50.018221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fddb8d73cfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cupos_primaria', sa.Integer(), nullable=True),
    sa.Column('cupos_secundaria', sa.Integer(), nullable=True),
    sa.Column('precio_matricula_primaria', sa.Float(), nullable=True),
    sa.Column('precio_matricula_secundaria', sa.Float(), nullable=True),
    sa.Column('precio_pension_primaria', sa.Float(), nullable=True),
    sa.Column('precio_pension_secundaria', sa.Float(), nullable=True),
    sa.Column('precio_recuperacion_primaria', sa.Float(), nullable=True),
    sa.Column('precio_recuperacion_secundaria', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_global_id'), 'configuracion_global', ['id'], unique=False)
    # NOTA DE SEGURIDAD: Se omitió la eliminación de las tablas de LangChain para preservar los embeddings de IA
    pass
    op.add_column('alumnos', sa.Column('estado_continuidad', sa.String(), nullable=True))
    op.drop_column('alumnos', 'intencion_continuidad')
    op.add_column('minedu_estandares', sa.Column('grado', sa.Integer(), nullable=True))
    op.drop_index('ix_minedu_estandares_ciclo', table_name='minedu_estandares')
    op.create_index(op.f('ix_minedu_estandares_grado'), 'minedu_estandares', ['grado'], unique=False)
    op.drop_column('minedu_estandares', 'ciclo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minedu_estandares', sa.Column('ciclo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_minedu_estandares_grado'), table_name='minedu_estandares')
    op.create_index('ix_minedu_estandares_ciclo', 'minedu_estandares', ['ciclo'], unique=False)
    op.drop_column('minedu_estandares', 'grado')
    op.add_column('alumnos', sa.Column('intencion_continuidad', sa.VARCHAR(), server_default=sa.text("'PENDIENTE'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('alumnos', 'estado_continuidad')
    # NOTA DE SEGURIDAD: No restaurar tablas de LangChain aquí, LangChain las maneja automáticamente
    pass
    op.drop_index(op.f('ix_configuracion_global_id'), table_name='configuracion_global')
    op.drop_table('configuracion_global')
    # ### end Alembic commands ###
