"""initial schema creation

Revision ID: bf9b4f001a20
Revises: 
Create Date: 2026-07-17 03:20:07.201680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9b4f001a20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_est', sa.String(), nullable=True),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('nombres', sa.String(), nullable=True),
    sa.Column('apellidos', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('promedio', sa.Float(), nullable=True),
    sa.Column('conducta', sa.String(), nullable=True),
    sa.Column('ap_nombre', sa.String(), nullable=True),
    sa.Column('ap_correo', sa.String(), nullable=True),
    sa.Column('ap_telefono', sa.String(), nullable=True),
    sa.Column('estado_proceso', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admisiones_codigo_est'), 'admisiones', ['codigo_est'], unique=True)
    op.create_index(op.f('ix_admisiones_id'), 'admisiones', ['id'], unique=False)
    op.create_table('anios_escolares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_cierre', sa.String(), nullable=True),
    sa.Column('inicio_matricula', sa.String(), nullable=True),
    sa.Column('fin_matricula', sa.String(), nullable=True),
    sa.Column('limite_rematricula', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anios_escolares_anio'), 'anios_escolares', ['anio'], unique=True)
    op.create_index(op.f('ix_anios_escolares_id'), 'anios_escolares', ['id'], unique=False)
    op.create_table('configuracion_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cupos_primaria', sa.Integer(), nullable=True),
    sa.Column('cupos_secundaria', sa.Integer(), nullable=True),
    sa.Column('precio_matricula_primaria', sa.Float(), nullable=True),
    sa.Column('precio_matricula_secundaria', sa.Float(), nullable=True),
    sa.Column('precio_pension_primaria', sa.Float(), nullable=True),
    sa.Column('precio_pension_secundaria', sa.Float(), nullable=True),
    sa.Column('precio_recuperacion_primaria', sa.Float(), nullable=True),
    sa.Column('precio_recuperacion_secundaria', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_global_id'), 'configuracion_global', ['id'], unique=False)
    op.create_table('minedu_competencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('curso_nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minedu_competencias_curso_nombre'), 'minedu_competencias', ['curso_nombre'], unique=False)
    op.create_index(op.f('ix_minedu_competencias_id'), 'minedu_competencias', ['id'], unique=False)
    op.create_index(op.f('ix_minedu_competencias_nivel'), 'minedu_competencias', ['nivel'], unique=False)
    op.create_table('minedu_desempenos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('curso_nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minedu_desempenos_curso_nombre'), 'minedu_desempenos', ['curso_nombre'], unique=False)
    op.create_index(op.f('ix_minedu_desempenos_grado'), 'minedu_desempenos', ['grado'], unique=False)
    op.create_index(op.f('ix_minedu_desempenos_id'), 'minedu_desempenos', ['id'], unique=False)
    op.create_index(op.f('ix_minedu_desempenos_nivel'), 'minedu_desempenos', ['nivel'], unique=False)
    op.create_table('minedu_estandares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('curso_nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minedu_estandares_curso_nombre'), 'minedu_estandares', ['curso_nombre'], unique=False)
    op.create_index(op.f('ix_minedu_estandares_grado'), 'minedu_estandares', ['grado'], unique=False)
    op.create_index(op.f('ix_minedu_estandares_id'), 'minedu_estandares', ['id'], unique=False)
    op.create_index(op.f('ix_minedu_estandares_nivel'), 'minedu_estandares', ['nivel'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('nivel_asignado', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('motivo_inactivo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_est', sa.String(), nullable=True),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('nombres', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.String(), nullable=True),
    sa.Column('apoderado_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('promedio_final', sa.Float(), nullable=True),
    sa.Column('estado_continuidad', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['apoderado_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_index(op.f('ix_alumnos_codigo_est'), 'alumnos', ['codigo_est'], unique=True)
    op.create_index(op.f('ix_alumnos_id'), 'alumnos', ['id'], unique=False)
    op.create_table('cajas_diarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('monto_apertura', sa.Float(), nullable=True),
    sa.Column('monto_cierre', sa.Float(), nullable=True),
    sa.Column('recaudado_sistema', sa.Float(), nullable=True),
    sa.Column('diferencia', sa.Float(), nullable=True),
    sa.Column('reporte_ia', sa.String(), nullable=True),
    sa.Column('secretario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secretario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cajas_diarias_id'), 'cajas_diarias', ['id'], unique=False)
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_escolar_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.String(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('docente_especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('curso_nombre', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docente_id', 'curso_nombre', 'nivel', name='uq_docente_especialidad')
    )
    op.create_index(op.f('ix_docente_especialidad_id'), 'docente_especialidad', ['id'], unique=False)
    op.create_table('minedu_capacidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competencia_id'], ['minedu_competencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minedu_capacidades_id'), 'minedu_capacidades', ['id'], unique=False)
    op.create_table('silabos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('curso_nombre', sa.String(), nullable=True),
    sa.Column('anno_escolar', sa.String(), nullable=True),
    sa.Column('datos_informativos', sa.Text(), nullable=True),
    sa.Column('fundamentacion', sa.Text(), nullable=True),
    sa.Column('proposito', sa.Text(), nullable=True),
    sa.Column('competencias', sa.Text(), nullable=True),
    sa.Column('capacidades', sa.Text(), nullable=True),
    sa.Column('estandares', sa.Text(), nullable=True),
    sa.Column('desempennos', sa.Text(), nullable=True),
    sa.Column('enfoques', sa.Text(), nullable=True),
    sa.Column('organizacion_unidades', sa.Text(), nullable=True),
    sa.Column('contenidos', sa.Text(), nullable=True),
    sa.Column('metodologia', sa.Text(), nullable=True),
    sa.Column('sistema_evaluacion', sa.Text(), nullable=True),
    sa.Column('materiales', sa.Text(), nullable=True),
    sa.Column('bibliografia', sa.Text(), nullable=True),
    sa.Column('bimestre_1', sa.Text(), nullable=True),
    sa.Column('bimestre_2', sa.Text(), nullable=True),
    sa.Column('bimestre_3', sa.Text(), nullable=True),
    sa.Column('bimestre_4', sa.Text(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silabos_curso_nombre'), 'silabos', ['curso_nombre'], unique=False)
    op.create_index(op.f('ix_silabos_grado'), 'silabos', ['grado'], unique=False)
    op.create_index(op.f('ix_silabos_id'), 'silabos', ['id'], unique=False)
    op.create_index(op.f('ix_silabos_nivel'), 'silabos', ['nivel'], unique=False)
    op.create_table('tarifarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_escolar_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('concepto', sa.String(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarifarios_id'), 'tarifarios', ['id'], unique=False)
    op.create_table('tutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_escolar_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutores_id'), 'tutores', ['id'], unique=False)
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_escolar_id', sa.Integer(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencia_id'), 'asistencia', ['id'], unique=False)
    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('anio_escolar_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('ruta_archivo', sa.String(), nullable=True),
    sa.Column('fecha_generacion', sa.String(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificados_id'), 'certificados', ['id'], unique=False)
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('codigo_obs', sa.String(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('psicologo_id', sa.Integer(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('dia', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('informe', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['psicologo_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_id'), 'citas', ['id'], unique=False)
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_escolar_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.String(), nullable=True),
    sa.Column('dia', sa.String(), nullable=True),
    sa.Column('hora_inicio', sa.String(), nullable=True),
    sa.Column('hora_fin', sa.String(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_id'), 'horarios', ['id'], unique=False)
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('anio_escolar_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.String(), nullable=True),
    sa.Column('promedio_final', sa.Float(), nullable=True),
    sa.Column('estado_final', sa.String(), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('estado_matricula', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'anio_escolar_id', name='uq_matricula_alumno_anio')
    )
    op.create_index(op.f('ix_matriculas_id'), 'matriculas', ['id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_escolar_id', sa.Integer(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('criterio', sa.String(), nullable=True),
    sa.Column('semana', sa.String(), nullable=True),
    sa.Column('valor_numerico', sa.Float(), nullable=True),
    sa.Column('valor_letra', sa.String(), nullable=True),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_id'), 'notas', ['id'], unique=False)
    op.create_table('observaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('texto', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observaciones_id'), 'observaciones', ['id'], unique=False)
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('concepto', sa.String(), nullable=True),
    sa.Column('metodo', sa.String(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.String(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas_diarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_id'), 'transacciones', ['id'], unique=False)
    op.create_table('cursos_recuperacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('nota_recuperacion', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_recuperacion_id'), 'cursos_recuperacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cursos_recuperacion_id'), table_name='cursos_recuperacion')
    op.drop_table('cursos_recuperacion')
    op.drop_index(op.f('ix_transacciones_id'), table_name='transacciones')
    op.drop_table('transacciones')
    op.drop_index(op.f('ix_observaciones_id'), table_name='observaciones')
    op.drop_table('observaciones')
    op.drop_index(op.f('ix_notas_id'), table_name='notas')
    op.drop_table('notas')
    op.drop_index(op.f('ix_matriculas_id'), table_name='matriculas')
    op.drop_table('matriculas')
    op.drop_index(op.f('ix_horarios_id'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_citas_id'), table_name='citas')
    op.drop_table('citas')
    op.drop_index(op.f('ix_certificados_id'), table_name='certificados')
    op.drop_table('certificados')
    op.drop_index(op.f('ix_asistencia_id'), table_name='asistencia')
    op.drop_table('asistencia')
    op.drop_index(op.f('ix_tutores_id'), table_name='tutores')
    op.drop_table('tutores')
    op.drop_index(op.f('ix_tarifarios_id'), table_name='tarifarios')
    op.drop_table('tarifarios')
    op.drop_index(op.f('ix_silabos_nivel'), table_name='silabos')
    op.drop_index(op.f('ix_silabos_id'), table_name='silabos')
    op.drop_index(op.f('ix_silabos_grado'), table_name='silabos')
    op.drop_index(op.f('ix_silabos_curso_nombre'), table_name='silabos')
    op.drop_table('silabos')
    op.drop_index(op.f('ix_minedu_capacidades_id'), table_name='minedu_capacidades')
    op.drop_table('minedu_capacidades')
    op.drop_index(op.f('ix_docente_especialidad_id'), table_name='docente_especialidad')
    op.drop_table('docente_especialidad')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_cajas_diarias_id'), table_name='cajas_diarias')
    op.drop_table('cajas_diarias')
    op.drop_index(op.f('ix_alumnos_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_codigo_est'), table_name='alumnos')
    op.drop_table('alumnos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_minedu_estandares_nivel'), table_name='minedu_estandares')
    op.drop_index(op.f('ix_minedu_estandares_id'), table_name='minedu_estandares')
    op.drop_index(op.f('ix_minedu_estandares_grado'), table_name='minedu_estandares')
    op.drop_index(op.f('ix_minedu_estandares_curso_nombre'), table_name='minedu_estandares')
    op.drop_table('minedu_estandares')
    op.drop_index(op.f('ix_minedu_desempenos_nivel'), table_name='minedu_desempenos')
    op.drop_index(op.f('ix_minedu_desempenos_id'), table_name='minedu_desempenos')
    op.drop_index(op.f('ix_minedu_desempenos_grado'), table_name='minedu_desempenos')
    op.drop_index(op.f('ix_minedu_desempenos_curso_nombre'), table_name='minedu_desempenos')
    op.drop_table('minedu_desempenos')
    op.drop_index(op.f('ix_minedu_competencias_nivel'), table_name='minedu_competencias')
    op.drop_index(op.f('ix_minedu_competencias_id'), table_name='minedu_competencias')
    op.drop_index(op.f('ix_minedu_competencias_curso_nombre'), table_name='minedu_competencias')
    op.drop_table('minedu_competencias')
    op.drop_index(op.f('ix_configuracion_global_id'), table_name='configuracion_global')
    op.drop_table('configuracion_global')
    op.drop_index(op.f('ix_anios_escolares_id'), table_name='anios_escolares')
    op.drop_index(op.f('ix_anios_escolares_anio'), table_name='anios_escolares')
    op.drop_table('anios_escolares')
    op.drop_index(op.f('ix_admisiones_id'), table_name='admisiones')
    op.drop_index(op.f('ix_admisiones_codigo_est'), table_name='admisiones')
    op.drop_table('admisiones')
    # ### end Alembic commands ###
